# Generated by Django 5.1.5 on 2025-01-29 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('age_rating', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('Movie', 'Movie'), ('TV Show', 'TV Show')], max_length=50)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('genre', models.CharField(max_length=50)),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('movie_upload', models.FileField(blank=True, null=True, upload_to='movies/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='movies/images/')),
            ],
        ),
    ]
