# Generated by Django 5.1.5 on 2025-01-28 09:25

import storages.backends.gcloud
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchhistory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='watchhistory',
            name='series',
        ),
        migrations.RemoveField(
            model_name='watchhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='series',
            name='stream_url',
        ),
        migrations.AddField(
            model_name='episode',
            name='stream_file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='episodes/'),
        ),
        migrations.AddField(
            model_name='series',
            name='stream_file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='series/'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='WatchHistory',
        ),
    ]
