# Generated by Django 5.1.5 on 2025-01-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_alter_watchhistory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='cast',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='series',
            name='genres',
            field=models.CharField(max_length=50),
        ),
    ]
